@echo off
echo Activating virtual environment...
call venv\Scripts\activate
echo Starting MongoDB service (if it exists)...
net start MongoDBServer
echo Running Django development server...
python manage.py runserver
pause